name: test-2
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "I'm job-1"
  job-2:
    needs: job-1
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "I'm job-2"
