name: simple
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: exit 1
  job-2:
    needs: job-1
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "I'm job-2"
  job-3:
    needs: job-2
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "I'm job-2"
